all:
  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host:       mail.interagis.com
          port:       465
          encryption: ssl
          username:   test@interagis.com
          password:   12345
          
          #swiss... not working
          #host:       188.62.108.33
          #port:       25
          #encryption: ssl
          #username:   Quiz
          #password:   123Swiss