<?php


/**
 * Base class that represents a query for the 'Pictures' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:30 2011
 *
 * @method     PicturesQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     PicturesQuery orderByDestinationId($order = Criteria::ASC) Order by the Destination_id column
 * @method     PicturesQuery orderByTitle($order = Criteria::ASC) Order by the title column
 * @method     PicturesQuery orderByPath($order = Criteria::ASC) Order by the path column
 * @method     PicturesQuery orderByLink($order = Criteria::ASC) Order by the link column
 * @method     PicturesQuery orderByAuthor($order = Criteria::ASC) Order by the author column
 *
 * @method     PicturesQuery groupById() Group by the id column
 * @method     PicturesQuery groupByDestinationId() Group by the Destination_id column
 * @method     PicturesQuery groupByTitle() Group by the title column
 * @method     PicturesQuery groupByPath() Group by the path column
 * @method     PicturesQuery groupByLink() Group by the link column
 * @method     PicturesQuery groupByAuthor() Group by the author column
 *
 * @method     PicturesQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     PicturesQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     PicturesQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     PicturesQuery leftJoinDestination($relationAlias = null) Adds a LEFT JOIN clause to the query using the Destination relation
 * @method     PicturesQuery rightJoinDestination($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Destination relation
 * @method     PicturesQuery innerJoinDestination($relationAlias = null) Adds a INNER JOIN clause to the query using the Destination relation
 *
 * @method     Pictures findOne(PropelPDO $con = null) Return the first Pictures matching the query
 * @method     Pictures findOneOrCreate(PropelPDO $con = null) Return the first Pictures matching the query, or a new Pictures object populated from the query conditions when no match is found
 *
 * @method     Pictures findOneById(int $id) Return the first Pictures filtered by the id column
 * @method     Pictures findOneByDestinationId(int $Destination_id) Return the first Pictures filtered by the Destination_id column
 * @method     Pictures findOneByTitle(string $title) Return the first Pictures filtered by the title column
 * @method     Pictures findOneByPath(string $path) Return the first Pictures filtered by the path column
 * @method     Pictures findOneByLink(string $link) Return the first Pictures filtered by the link column
 * @method     Pictures findOneByAuthor(string $author) Return the first Pictures filtered by the author column
 *
 * @method     array findById(int $id) Return Pictures objects filtered by the id column
 * @method     array findByDestinationId(int $Destination_id) Return Pictures objects filtered by the Destination_id column
 * @method     array findByTitle(string $title) Return Pictures objects filtered by the title column
 * @method     array findByPath(string $path) Return Pictures objects filtered by the path column
 * @method     array findByLink(string $link) Return Pictures objects filtered by the link column
 * @method     array findByAuthor(string $author) Return Pictures objects filtered by the author column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BasePicturesQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BasePicturesQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Pictures', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new PicturesQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    PicturesQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof PicturesQuery) {
			return $criteria;
		}
		$query = new PicturesQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Pictures|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = PicturesPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(PicturesPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(PicturesPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(PicturesPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the Destination_id column
	 * 
	 * @param     int|array $destinationId The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByDestinationId($destinationId = null, $comparison = null)
	{
		if (is_array($destinationId)) {
			$useMinMax = false;
			if (isset($destinationId['min'])) {
				$this->addUsingAlias(PicturesPeer::DESTINATION_ID, $destinationId['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($destinationId['max'])) {
				$this->addUsingAlias(PicturesPeer::DESTINATION_ID, $destinationId['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(PicturesPeer::DESTINATION_ID, $destinationId, $comparison);
	}

	/**
	 * Filter the query on the title column
	 * 
	 * @param     string $title The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByTitle($title = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($title)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $title)) {
				$title = str_replace('*', '%', $title);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(PicturesPeer::TITLE, $title, $comparison);
	}

	/**
	 * Filter the query on the path column
	 * 
	 * @param     string $path The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByPath($path = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($path)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $path)) {
				$path = str_replace('*', '%', $path);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(PicturesPeer::PATH, $path, $comparison);
	}

	/**
	 * Filter the query on the link column
	 * 
	 * @param     string $link The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByLink($link = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($link)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $link)) {
				$link = str_replace('*', '%', $link);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(PicturesPeer::LINK, $link, $comparison);
	}

	/**
	 * Filter the query on the author column
	 * 
	 * @param     string $author The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByAuthor($author = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($author)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $author)) {
				$author = str_replace('*', '%', $author);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(PicturesPeer::AUTHOR, $author, $comparison);
	}

	/**
	 * Filter the query by a related Destination object
	 *
	 * @param     Destination $destination  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function filterByDestination($destination, $comparison = null)
	{
		return $this
			->addUsingAlias(PicturesPeer::DESTINATION_ID, $destination->getId(), $comparison);
	}

	/**
	 * Adds a JOIN clause to the query using the Destination relation
	 * 
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function joinDestination($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('Destination');
		
		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}
		
		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'Destination');
		}
		
		return $this;
	}

	/**
	 * Use the Destination relation Destination object
	 *
	 * @see       useQuery()
	 * 
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    DestinationQuery A secondary query class using the current class as primary query
	 */
	public function useDestinationQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
	{
		return $this
			->joinDestination($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'Destination', 'DestinationQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Pictures $pictures Object to remove from the list of results
	 *
	 * @return    PicturesQuery The current query, for fluid interface
	 */
	public function prune($pictures = null)
	{
		if ($pictures) {
			$this->addUsingAlias(PicturesPeer::ID, $pictures->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BasePicturesQuery
