<?php


/**
 * Base class that represents a row from the 'Flight' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:29 2011
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseFlight extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
  const PEER = 'FlightPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FlightPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the friend_id field.
	 * @var        int
	 */
	protected $friend_id;

	/**
	 * The value for the start_location_id field.
	 * @var        int
	 */
	protected $start_location_id;

	/**
	 * The value for the target_location_id field.
	 * @var        int
	 */
	protected $target_location_id;

	/**
	 * The value for the flight_type field.
	 * @var        string
	 */
	protected $flight_type;

	/**
	 * The value for the flight_start field.
	 * @var        string
	 */
	protected $flight_start;

	/**
	 * The value for the flight_end field.
	 * @var        string
	 */
	protected $flight_end;

	/**
	 * The value for the flight_duration field.
	 * @var        int
	 */
	protected $flight_duration;

	/**
	 * The value for the flight_accepted field.
	 * @var        string
	 */
	protected $flight_accepted;

	/**
	 * The value for the landing_notification field.
	 * @var        boolean
	 */
	protected $landing_notification;

	/**
	 * @var        User
	 */
	protected $aUser;

	/**
	 * @var        Friend
	 */
	protected $aFriend;

	/**
	 * @var        Location
	 */
	protected $aLocationRelatedByStartLocationId;

	/**
	 * @var        Location
	 */
	protected $aLocationRelatedByTargetLocationId;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [friend_id] column value.
	 * 
	 * @return     int
	 */
	public function getFriendId()
	{
		return $this->friend_id;
	}

	/**
	 * Get the [start_location_id] column value.
	 * 
	 * @return     int
	 */
	public function getStartLocationId()
	{
		return $this->start_location_id;
	}

	/**
	 * Get the [target_location_id] column value.
	 * 
	 * @return     int
	 */
	public function getTargetLocationId()
	{
		return $this->target_location_id;
	}

	/**
	 * Get the [flight_type] column value.
	 * freund der angeflogen wird
	 * @return     string
	 */
	public function getFlightType()
	{
		return $this->flight_type;
	}

	/**
	 * Get the [optionally formatted] temporal [flight_start] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFlightStart($format = 'Y-m-d H:i:s')
	{
		if ($this->flight_start === null) {
			return null;
		}


		if ($this->flight_start === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->flight_start);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->flight_start, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [flight_end] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFlightEnd($format = 'Y-m-d H:i:s')
	{
		if ($this->flight_end === null) {
			return null;
		}


		if ($this->flight_end === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->flight_end);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->flight_end, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [flight_duration] column value.
	 * in sekunden... kann man dann immer noch umrechnen?
	 * @return     int
	 */
	public function getFlightDuration()
	{
		return $this->flight_duration;
	}

	/**
	 * Get the [flight_accepted] column value.
	 * 
	 * @return     string
	 */
	public function getFlightAccepted()
	{
		return $this->flight_accepted;
	}

	/**
	 * Get the [landing_notification] column value.
	 * 
	 * @return     boolean
	 */
	public function getLandingNotification()
	{
		return $this->landing_notification;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = FlightPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = FlightPeer::USER_ID;
		}

		if ($this->aUser !== null && $this->aUser->getId() !== $v) {
			$this->aUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [friend_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFriendId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->friend_id !== $v) {
			$this->friend_id = $v;
			$this->modifiedColumns[] = FlightPeer::FRIEND_ID;
		}

		if ($this->aFriend !== null && $this->aFriend->getId() !== $v) {
			$this->aFriend = null;
		}

		return $this;
	} // setFriendId()

	/**
	 * Set the value of [start_location_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setStartLocationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->start_location_id !== $v) {
			$this->start_location_id = $v;
			$this->modifiedColumns[] = FlightPeer::START_LOCATION_ID;
		}

		if ($this->aLocationRelatedByStartLocationId !== null && $this->aLocationRelatedByStartLocationId->getId() !== $v) {
			$this->aLocationRelatedByStartLocationId = null;
		}

		return $this;
	} // setStartLocationId()

	/**
	 * Set the value of [target_location_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setTargetLocationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->target_location_id !== $v) {
			$this->target_location_id = $v;
			$this->modifiedColumns[] = FlightPeer::TARGET_LOCATION_ID;
		}

		if ($this->aLocationRelatedByTargetLocationId !== null && $this->aLocationRelatedByTargetLocationId->getId() !== $v) {
			$this->aLocationRelatedByTargetLocationId = null;
		}

		return $this;
	} // setTargetLocationId()

	/**
	 * Set the value of [flight_type] column.
	 * freund der angeflogen wird
	 * @param      string $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFlightType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flight_type !== $v) {
			$this->flight_type = $v;
			$this->modifiedColumns[] = FlightPeer::FLIGHT_TYPE;
		}

		return $this;
	} // setFlightType()

	/**
	 * Sets the value of [flight_start] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFlightStart($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->flight_start !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->flight_start !== null && $tmpDt = new DateTime($this->flight_start)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->flight_start = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FlightPeer::FLIGHT_START;
			}
		} // if either are not null

		return $this;
	} // setFlightStart()

	/**
	 * Sets the value of [flight_end] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFlightEnd($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->flight_end !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->flight_end !== null && $tmpDt = new DateTime($this->flight_end)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->flight_end = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FlightPeer::FLIGHT_END;
			}
		} // if either are not null

		return $this;
	} // setFlightEnd()

	/**
	 * Set the value of [flight_duration] column.
	 * in sekunden... kann man dann immer noch umrechnen?
	 * @param      int $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFlightDuration($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->flight_duration !== $v) {
			$this->flight_duration = $v;
			$this->modifiedColumns[] = FlightPeer::FLIGHT_DURATION;
		}

		return $this;
	} // setFlightDuration()

	/**
	 * Set the value of [flight_accepted] column.
	 * 
	 * @param      string $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setFlightAccepted($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flight_accepted !== $v) {
			$this->flight_accepted = $v;
			$this->modifiedColumns[] = FlightPeer::FLIGHT_ACCEPTED;
		}

		return $this;
	} // setFlightAccepted()

	/**
	 * Set the value of [landing_notification] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Flight The current object (for fluent API support)
	 */
	public function setLandingNotification($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->landing_notification !== $v) {
			$this->landing_notification = $v;
			$this->modifiedColumns[] = FlightPeer::LANDING_NOTIFICATION;
		}

		return $this;
	} // setLandingNotification()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->friend_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->start_location_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->target_location_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->flight_type = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->flight_start = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->flight_end = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->flight_duration = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->flight_accepted = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->landing_notification = ($row[$startcol + 10] !== null) ? (boolean) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 11; // 11 = FlightPeer::NUM_COLUMNS - FlightPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Flight object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUser !== null && $this->user_id !== $this->aUser->getId()) {
			$this->aUser = null;
		}
		if ($this->aFriend !== null && $this->friend_id !== $this->aFriend->getId()) {
			$this->aFriend = null;
		}
		if ($this->aLocationRelatedByStartLocationId !== null && $this->start_location_id !== $this->aLocationRelatedByStartLocationId->getId()) {
			$this->aLocationRelatedByStartLocationId = null;
		}
		if ($this->aLocationRelatedByTargetLocationId !== null && $this->target_location_id !== $this->aLocationRelatedByTargetLocationId->getId()) {
			$this->aLocationRelatedByTargetLocationId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FlightPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FlightPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUser = null;
			$this->aFriend = null;
			$this->aLocationRelatedByStartLocationId = null;
			$this->aLocationRelatedByTargetLocationId = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FlightPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFlight:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}
			
			if ($ret) {
				FlightQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFlight:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}
				
				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FlightPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFlight:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFlight:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}
				
				FlightPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUser !== null) {
				if ($this->aUser->isModified() || $this->aUser->isNew()) {
					$affectedRows += $this->aUser->save($con);
				}
				$this->setUser($this->aUser);
			}

			if ($this->aFriend !== null) {
				if ($this->aFriend->isModified() || $this->aFriend->isNew()) {
					$affectedRows += $this->aFriend->save($con);
				}
				$this->setFriend($this->aFriend);
			}

			if ($this->aLocationRelatedByStartLocationId !== null) {
				if ($this->aLocationRelatedByStartLocationId->isModified() || $this->aLocationRelatedByStartLocationId->isNew()) {
					$affectedRows += $this->aLocationRelatedByStartLocationId->save($con);
				}
				$this->setLocationRelatedByStartLocationId($this->aLocationRelatedByStartLocationId);
			}

			if ($this->aLocationRelatedByTargetLocationId !== null) {
				if ($this->aLocationRelatedByTargetLocationId->isModified() || $this->aLocationRelatedByTargetLocationId->isNew()) {
					$affectedRows += $this->aLocationRelatedByTargetLocationId->save($con);
				}
				$this->setLocationRelatedByTargetLocationId($this->aLocationRelatedByTargetLocationId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FlightPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(FlightPeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.FlightPeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows += 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows += FlightPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUser !== null) {
				if (!$this->aUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUser->getValidationFailures());
				}
			}

			if ($this->aFriend !== null) {
				if (!$this->aFriend->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFriend->getValidationFailures());
				}
			}

			if ($this->aLocationRelatedByStartLocationId !== null) {
				if (!$this->aLocationRelatedByStartLocationId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLocationRelatedByStartLocationId->getValidationFailures());
				}
			}

			if ($this->aLocationRelatedByTargetLocationId !== null) {
				if (!$this->aLocationRelatedByTargetLocationId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aLocationRelatedByTargetLocationId->getValidationFailures());
				}
			}


			if (($retval = FlightPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FlightPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserId();
				break;
			case 2:
				return $this->getFriendId();
				break;
			case 3:
				return $this->getStartLocationId();
				break;
			case 4:
				return $this->getTargetLocationId();
				break;
			case 5:
				return $this->getFlightType();
				break;
			case 6:
				return $this->getFlightStart();
				break;
			case 7:
				return $this->getFlightEnd();
				break;
			case 8:
				return $this->getFlightDuration();
				break;
			case 9:
				return $this->getFlightAccepted();
				break;
			case 10:
				return $this->getLandingNotification();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. 
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $includeForeignObjects = false)
	{
		$keys = FlightPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserId(),
			$keys[2] => $this->getFriendId(),
			$keys[3] => $this->getStartLocationId(),
			$keys[4] => $this->getTargetLocationId(),
			$keys[5] => $this->getFlightType(),
			$keys[6] => $this->getFlightStart(),
			$keys[7] => $this->getFlightEnd(),
			$keys[8] => $this->getFlightDuration(),
			$keys[9] => $this->getFlightAccepted(),
			$keys[10] => $this->getLandingNotification(),
		);
		if ($includeForeignObjects) {
			if (null !== $this->aUser) {
				$result['User'] = $this->aUser->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aFriend) {
				$result['Friend'] = $this->aFriend->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aLocationRelatedByStartLocationId) {
				$result['LocationRelatedByStartLocationId'] = $this->aLocationRelatedByStartLocationId->toArray($keyType, $includeLazyLoadColumns, true);
			}
			if (null !== $this->aLocationRelatedByTargetLocationId) {
				$result['LocationRelatedByTargetLocationId'] = $this->aLocationRelatedByTargetLocationId->toArray($keyType, $includeLazyLoadColumns, true);
			}
		}
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FlightPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserId($value);
				break;
			case 2:
				$this->setFriendId($value);
				break;
			case 3:
				$this->setStartLocationId($value);
				break;
			case 4:
				$this->setTargetLocationId($value);
				break;
			case 5:
				$this->setFlightType($value);
				break;
			case 6:
				$this->setFlightStart($value);
				break;
			case 7:
				$this->setFlightEnd($value);
				break;
			case 8:
				$this->setFlightDuration($value);
				break;
			case 9:
				$this->setFlightAccepted($value);
				break;
			case 10:
				$this->setLandingNotification($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FlightPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFriendId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setStartLocationId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTargetLocationId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFlightType($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFlightStart($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFlightEnd($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFlightDuration($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFlightAccepted($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setLandingNotification($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FlightPeer::DATABASE_NAME);

		if ($this->isColumnModified(FlightPeer::ID)) $criteria->add(FlightPeer::ID, $this->id);
		if ($this->isColumnModified(FlightPeer::USER_ID)) $criteria->add(FlightPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(FlightPeer::FRIEND_ID)) $criteria->add(FlightPeer::FRIEND_ID, $this->friend_id);
		if ($this->isColumnModified(FlightPeer::START_LOCATION_ID)) $criteria->add(FlightPeer::START_LOCATION_ID, $this->start_location_id);
		if ($this->isColumnModified(FlightPeer::TARGET_LOCATION_ID)) $criteria->add(FlightPeer::TARGET_LOCATION_ID, $this->target_location_id);
		if ($this->isColumnModified(FlightPeer::FLIGHT_TYPE)) $criteria->add(FlightPeer::FLIGHT_TYPE, $this->flight_type);
		if ($this->isColumnModified(FlightPeer::FLIGHT_START)) $criteria->add(FlightPeer::FLIGHT_START, $this->flight_start);
		if ($this->isColumnModified(FlightPeer::FLIGHT_END)) $criteria->add(FlightPeer::FLIGHT_END, $this->flight_end);
		if ($this->isColumnModified(FlightPeer::FLIGHT_DURATION)) $criteria->add(FlightPeer::FLIGHT_DURATION, $this->flight_duration);
		if ($this->isColumnModified(FlightPeer::FLIGHT_ACCEPTED)) $criteria->add(FlightPeer::FLIGHT_ACCEPTED, $this->flight_accepted);
		if ($this->isColumnModified(FlightPeer::LANDING_NOTIFICATION)) $criteria->add(FlightPeer::LANDING_NOTIFICATION, $this->landing_notification);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FlightPeer::DATABASE_NAME);
		$criteria->add(FlightPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Flight (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setUserId($this->user_id);
		$copyObj->setFriendId($this->friend_id);
		$copyObj->setStartLocationId($this->start_location_id);
		$copyObj->setTargetLocationId($this->target_location_id);
		$copyObj->setFlightType($this->flight_type);
		$copyObj->setFlightStart($this->flight_start);
		$copyObj->setFlightEnd($this->flight_end);
		$copyObj->setFlightDuration($this->flight_duration);
		$copyObj->setFlightAccepted($this->flight_accepted);
		$copyObj->setLandingNotification($this->landing_notification);

		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Flight Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FlightPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FlightPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a User object.
	 *
	 * @param      User $v
	 * @return     Flight The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUser(User $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->aUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the User object, it will not be re-added.
		if ($v !== null) {
			$v->addFlight($this);
		}

		return $this;
	}


	/**
	 * Get the associated User object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     User The associated User object.
	 * @throws     PropelException
	 */
	public function getUser(PropelPDO $con = null)
	{
		if ($this->aUser === null && ($this->user_id !== null)) {
			$this->aUser = UserQuery::create()->findPk($this->user_id, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUser->addFlights($this);
			 */
		}
		return $this->aUser;
	}

	/**
	 * Declares an association between this object and a Friend object.
	 *
	 * @param      Friend $v
	 * @return     Flight The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFriend(Friend $v = null)
	{
		if ($v === null) {
			$this->setFriendId(NULL);
		} else {
			$this->setFriendId($v->getId());
		}

		$this->aFriend = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Friend object, it will not be re-added.
		if ($v !== null) {
			$v->addFlight($this);
		}

		return $this;
	}


	/**
	 * Get the associated Friend object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Friend The associated Friend object.
	 * @throws     PropelException
	 */
	public function getFriend(PropelPDO $con = null)
	{
		if ($this->aFriend === null && ($this->friend_id !== null)) {
			$this->aFriend = FriendQuery::create()->findPk($this->friend_id, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFriend->addFlights($this);
			 */
		}
		return $this->aFriend;
	}

	/**
	 * Declares an association between this object and a Location object.
	 *
	 * @param      Location $v
	 * @return     Flight The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLocationRelatedByStartLocationId(Location $v = null)
	{
		if ($v === null) {
			$this->setStartLocationId(NULL);
		} else {
			$this->setStartLocationId($v->getId());
		}

		$this->aLocationRelatedByStartLocationId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Location object, it will not be re-added.
		if ($v !== null) {
			$v->addFlightRelatedByStartLocationId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Location object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Location The associated Location object.
	 * @throws     PropelException
	 */
	public function getLocationRelatedByStartLocationId(PropelPDO $con = null)
	{
		if ($this->aLocationRelatedByStartLocationId === null && ($this->start_location_id !== null)) {
			$this->aLocationRelatedByStartLocationId = LocationQuery::create()->findPk($this->start_location_id, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLocationRelatedByStartLocationId->addFlightsRelatedByStartLocationId($this);
			 */
		}
		return $this->aLocationRelatedByStartLocationId;
	}

	/**
	 * Declares an association between this object and a Location object.
	 *
	 * @param      Location $v
	 * @return     Flight The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setLocationRelatedByTargetLocationId(Location $v = null)
	{
		if ($v === null) {
			$this->setTargetLocationId(NULL);
		} else {
			$this->setTargetLocationId($v->getId());
		}

		$this->aLocationRelatedByTargetLocationId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Location object, it will not be re-added.
		if ($v !== null) {
			$v->addFlightRelatedByTargetLocationId($this);
		}

		return $this;
	}


	/**
	 * Get the associated Location object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Location The associated Location object.
	 * @throws     PropelException
	 */
	public function getLocationRelatedByTargetLocationId(PropelPDO $con = null)
	{
		if ($this->aLocationRelatedByTargetLocationId === null && ($this->target_location_id !== null)) {
			$this->aLocationRelatedByTargetLocationId = LocationQuery::create()->findPk($this->target_location_id, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aLocationRelatedByTargetLocationId->addFlightsRelatedByTargetLocationId($this);
			 */
		}
		return $this->aLocationRelatedByTargetLocationId;
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->user_id = null;
		$this->friend_id = null;
		$this->start_location_id = null;
		$this->target_location_id = null;
		$this->flight_type = null;
		$this->flight_start = null;
		$this->flight_end = null;
		$this->flight_duration = null;
		$this->flight_accepted = null;
		$this->landing_notification = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->aUser = null;
		$this->aFriend = null;
		$this->aLocationRelatedByStartLocationId = null;
		$this->aLocationRelatedByTargetLocationId = null;
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseFlight:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}
		
		if (preg_match('/get(\w+)/', $name, $matches)) {
			$virtualColumn = $matches[1];
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
			// no lcfirst in php<5.3...
			$virtualColumn[0] = strtolower($virtualColumn[0]);
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
		}
		return parent::__call($name, $params);
	}

} // BaseFlight
