<?php


/**
 * Base class that represents a row from the 'Destination' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:29 2011
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseDestination extends BaseObject  implements Persistent
{

	/**
	 * Peer class name
	 */
  const PEER = 'DestinationPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        DestinationPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the location_id field.
	 * @var        int
	 */
	protected $location_id;

	/**
	 * The value for the location_name field.
	 * @var        string
	 */
	protected $location_name;

	/**
	 * The value for the region field.
	 * @var        string
	 */
	protected $region;

	/**
	 * The value for the geolocation field.
	 * @var        string
	 */
	protected $geolocation;

	/**
	 * The value for the area field.
	 * @var        string
	 */
	protected $area;

	/**
	 * The value for the elevation field.
	 * @var        string
	 */
	protected $elevation;

	/**
	 * The value for the population field.
	 * @var        string
	 */
	protected $population;

	/**
	 * The value for the infotext field.
	 * @var        string
	 */
	protected $infotext;

	/**
	 * The value for the population_density field.
	 * @var        string
	 */
	protected $population_density;

	/**
	 * The value for the airport_name field.
	 * @var        string
	 */
	protected $airport_name;

	/**
	 * The value for the airport_abbr field.
	 * @var        string
	 */
	protected $airport_abbr;

	/**
	 * The value for the airport_type field.
	 * @var        string
	 */
	protected $airport_type;

	/**
	 * The value for the timezone field.
	 * @var        string
	 */
	protected $timezone;

	/**
	 * @var        array Pictures[] Collection to store aggregation of Pictures objects.
	 */
	protected $collPicturess;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [location_id] column value.
	 * 
	 * @return     int
	 */
	public function getLocationId()
	{
		return $this->location_id;
	}

	/**
	 * Get the [location_name] column value.
	 * 
	 * @return     string
	 */
	public function getLocationName()
	{
		return $this->location_name;
	}

	/**
	 * Get the [region] column value.
	 * 
	 * @return     string
	 */
	public function getRegion()
	{
		return $this->region;
	}

	/**
	 * Get the [geolocation] column value.
	 * 
	 * @return     string
	 */
	public function getGeolocation()
	{
		return $this->geolocation;
	}

	/**
	 * Get the [area] column value.
	 * 
	 * @return     string
	 */
	public function getArea()
	{
		return $this->area;
	}

	/**
	 * Get the [elevation] column value.
	 * 
	 * @return     string
	 */
	public function getElevation()
	{
		return $this->elevation;
	}

	/**
	 * Get the [population] column value.
	 * 
	 * @return     string
	 */
	public function getPopulation()
	{
		return $this->population;
	}

	/**
	 * Get the [infotext] column value.
	 * 
	 * @return     string
	 */
	public function getInfotext()
	{
		return $this->infotext;
	}

	/**
	 * Get the [population_density] column value.
	 * 
	 * @return     string
	 */
	public function getPopulationDensity()
	{
		return $this->population_density;
	}

	/**
	 * Get the [airport_name] column value.
	 * 
	 * @return     string
	 */
	public function getAirportName()
	{
		return $this->airport_name;
	}

	/**
	 * Get the [airport_abbr] column value.
	 * 
	 * @return     string
	 */
	public function getAirportAbbr()
	{
		return $this->airport_abbr;
	}

	/**
	 * Get the [airport_type] column value.
	 * 
	 * @return     string
	 */
	public function getAirportType()
	{
		return $this->airport_type;
	}

	/**
	 * Get the [timezone] column value.
	 * 
	 * @return     string
	 */
	public function getTimezone()
	{
		return $this->timezone;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = DestinationPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [location_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setLocationId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->location_id !== $v) {
			$this->location_id = $v;
			$this->modifiedColumns[] = DestinationPeer::LOCATION_ID;
		}

		return $this;
	} // setLocationId()

	/**
	 * Set the value of [location_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setLocationName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->location_name !== $v) {
			$this->location_name = $v;
			$this->modifiedColumns[] = DestinationPeer::LOCATION_NAME;
		}

		return $this;
	} // setLocationName()

	/**
	 * Set the value of [region] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setRegion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->region !== $v) {
			$this->region = $v;
			$this->modifiedColumns[] = DestinationPeer::REGION;
		}

		return $this;
	} // setRegion()

	/**
	 * Set the value of [geolocation] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setGeolocation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->geolocation !== $v) {
			$this->geolocation = $v;
			$this->modifiedColumns[] = DestinationPeer::GEOLOCATION;
		}

		return $this;
	} // setGeolocation()

	/**
	 * Set the value of [area] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setArea($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->area !== $v) {
			$this->area = $v;
			$this->modifiedColumns[] = DestinationPeer::AREA;
		}

		return $this;
	} // setArea()

	/**
	 * Set the value of [elevation] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setElevation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->elevation !== $v) {
			$this->elevation = $v;
			$this->modifiedColumns[] = DestinationPeer::ELEVATION;
		}

		return $this;
	} // setElevation()

	/**
	 * Set the value of [population] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setPopulation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->population !== $v) {
			$this->population = $v;
			$this->modifiedColumns[] = DestinationPeer::POPULATION;
		}

		return $this;
	} // setPopulation()

	/**
	 * Set the value of [infotext] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setInfotext($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->infotext !== $v) {
			$this->infotext = $v;
			$this->modifiedColumns[] = DestinationPeer::INFOTEXT;
		}

		return $this;
	} // setInfotext()

	/**
	 * Set the value of [population_density] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setPopulationDensity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->population_density !== $v) {
			$this->population_density = $v;
			$this->modifiedColumns[] = DestinationPeer::POPULATION_DENSITY;
		}

		return $this;
	} // setPopulationDensity()

	/**
	 * Set the value of [airport_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setAirportName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->airport_name !== $v) {
			$this->airport_name = $v;
			$this->modifiedColumns[] = DestinationPeer::AIRPORT_NAME;
		}

		return $this;
	} // setAirportName()

	/**
	 * Set the value of [airport_abbr] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setAirportAbbr($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->airport_abbr !== $v) {
			$this->airport_abbr = $v;
			$this->modifiedColumns[] = DestinationPeer::AIRPORT_ABBR;
		}

		return $this;
	} // setAirportAbbr()

	/**
	 * Set the value of [airport_type] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setAirportType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->airport_type !== $v) {
			$this->airport_type = $v;
			$this->modifiedColumns[] = DestinationPeer::AIRPORT_TYPE;
		}

		return $this;
	} // setAirportType()

	/**
	 * Set the value of [timezone] column.
	 * 
	 * @param      string $v new value
	 * @return     Destination The current object (for fluent API support)
	 */
	public function setTimezone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->timezone !== $v) {
			$this->timezone = $v;
			$this->modifiedColumns[] = DestinationPeer::TIMEZONE;
		}

		return $this;
	} // setTimezone()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->location_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->location_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->region = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->geolocation = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->area = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->elevation = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->population = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->infotext = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->population_density = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->airport_name = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->airport_abbr = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->airport_type = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->timezone = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			return $startcol + 14; // 14 = DestinationPeer::NUM_COLUMNS - DestinationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Destination object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DestinationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = DestinationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collPicturess = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DestinationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDestination:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			    return;
			  }
			}
			
			if ($ret) {
				DestinationQuery::create()
					->filterByPrimaryKey($this->getPrimaryKey())
					->delete($con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDestination:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}
				
				$con->commit();
				$this->setDeleted(true);
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(DestinationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseDestination:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			  	$con->commit();
			    return $affectedRows;
			  }
			}
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseDestination:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}
				
				DestinationPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = DestinationPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$criteria = $this->buildCriteria();
					if ($criteria->keyContainsValue(DestinationPeer::ID) ) {
						throw new PropelException('Cannot insert a value for auto-increment primary key ('.DestinationPeer::ID.')');
					}

					$pk = BasePeer::doInsert($criteria, $con);
					$affectedRows = 1;
					$this->setId($pk);  //[IMV] update autoincrement primary key
					$this->setNew(false);
				} else {
					$affectedRows = DestinationPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPicturess !== null) {
				foreach ($this->collPicturess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = DestinationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPicturess !== null) {
					foreach ($this->collPicturess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DestinationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getLocationId();
				break;
			case 2:
				return $this->getLocationName();
				break;
			case 3:
				return $this->getRegion();
				break;
			case 4:
				return $this->getGeolocation();
				break;
			case 5:
				return $this->getArea();
				break;
			case 6:
				return $this->getElevation();
				break;
			case 7:
				return $this->getPopulation();
				break;
			case 8:
				return $this->getInfotext();
				break;
			case 9:
				return $this->getPopulationDensity();
				break;
			case 10:
				return $this->getAirportName();
				break;
			case 11:
				return $this->getAirportAbbr();
				break;
			case 12:
				return $this->getAirportType();
				break;
			case 13:
				return $this->getTimezone();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. 
	 *                    Defaults to BasePeer::TYPE_PHPNAME.
	 * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to TRUE.
	 *
	 * @return    array an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = DestinationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getLocationId(),
			$keys[2] => $this->getLocationName(),
			$keys[3] => $this->getRegion(),
			$keys[4] => $this->getGeolocation(),
			$keys[5] => $this->getArea(),
			$keys[6] => $this->getElevation(),
			$keys[7] => $this->getPopulation(),
			$keys[8] => $this->getInfotext(),
			$keys[9] => $this->getPopulationDensity(),
			$keys[10] => $this->getAirportName(),
			$keys[11] => $this->getAirportAbbr(),
			$keys[12] => $this->getAirportType(),
			$keys[13] => $this->getTimezone(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = DestinationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setLocationId($value);
				break;
			case 2:
				$this->setLocationName($value);
				break;
			case 3:
				$this->setRegion($value);
				break;
			case 4:
				$this->setGeolocation($value);
				break;
			case 5:
				$this->setArea($value);
				break;
			case 6:
				$this->setElevation($value);
				break;
			case 7:
				$this->setPopulation($value);
				break;
			case 8:
				$this->setInfotext($value);
				break;
			case 9:
				$this->setPopulationDensity($value);
				break;
			case 10:
				$this->setAirportName($value);
				break;
			case 11:
				$this->setAirportAbbr($value);
				break;
			case 12:
				$this->setAirportType($value);
				break;
			case 13:
				$this->setTimezone($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = DestinationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setLocationId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setLocationName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setRegion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGeolocation($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setArea($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setElevation($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPopulation($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setInfotext($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setPopulationDensity($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setAirportName($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setAirportAbbr($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setAirportType($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setTimezone($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(DestinationPeer::DATABASE_NAME);

		if ($this->isColumnModified(DestinationPeer::ID)) $criteria->add(DestinationPeer::ID, $this->id);
		if ($this->isColumnModified(DestinationPeer::LOCATION_ID)) $criteria->add(DestinationPeer::LOCATION_ID, $this->location_id);
		if ($this->isColumnModified(DestinationPeer::LOCATION_NAME)) $criteria->add(DestinationPeer::LOCATION_NAME, $this->location_name);
		if ($this->isColumnModified(DestinationPeer::REGION)) $criteria->add(DestinationPeer::REGION, $this->region);
		if ($this->isColumnModified(DestinationPeer::GEOLOCATION)) $criteria->add(DestinationPeer::GEOLOCATION, $this->geolocation);
		if ($this->isColumnModified(DestinationPeer::AREA)) $criteria->add(DestinationPeer::AREA, $this->area);
		if ($this->isColumnModified(DestinationPeer::ELEVATION)) $criteria->add(DestinationPeer::ELEVATION, $this->elevation);
		if ($this->isColumnModified(DestinationPeer::POPULATION)) $criteria->add(DestinationPeer::POPULATION, $this->population);
		if ($this->isColumnModified(DestinationPeer::INFOTEXT)) $criteria->add(DestinationPeer::INFOTEXT, $this->infotext);
		if ($this->isColumnModified(DestinationPeer::POPULATION_DENSITY)) $criteria->add(DestinationPeer::POPULATION_DENSITY, $this->population_density);
		if ($this->isColumnModified(DestinationPeer::AIRPORT_NAME)) $criteria->add(DestinationPeer::AIRPORT_NAME, $this->airport_name);
		if ($this->isColumnModified(DestinationPeer::AIRPORT_ABBR)) $criteria->add(DestinationPeer::AIRPORT_ABBR, $this->airport_abbr);
		if ($this->isColumnModified(DestinationPeer::AIRPORT_TYPE)) $criteria->add(DestinationPeer::AIRPORT_TYPE, $this->airport_type);
		if ($this->isColumnModified(DestinationPeer::TIMEZONE)) $criteria->add(DestinationPeer::TIMEZONE, $this->timezone);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(DestinationPeer::DATABASE_NAME);
		$criteria->add(DestinationPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Returns true if the primary key for this object is null.
	 * @return     boolean
	 */
	public function isPrimaryKeyNull()
	{
		return null === $this->getId();
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Destination (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{
		$copyObj->setLocationId($this->location_id);
		$copyObj->setLocationName($this->location_name);
		$copyObj->setRegion($this->region);
		$copyObj->setGeolocation($this->geolocation);
		$copyObj->setArea($this->area);
		$copyObj->setElevation($this->elevation);
		$copyObj->setPopulation($this->population);
		$copyObj->setInfotext($this->infotext);
		$copyObj->setPopulationDensity($this->population_density);
		$copyObj->setAirportName($this->airport_name);
		$copyObj->setAirportAbbr($this->airport_abbr);
		$copyObj->setAirportType($this->airport_type);
		$copyObj->setTimezone($this->timezone);

		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPicturess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPictures($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);
		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value
	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Destination Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     DestinationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new DestinationPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collPicturess collection
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPicturess()
	 */
	public function clearPicturess()
	{
		$this->collPicturess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPicturess collection.
	 *
	 * By default this just sets the collPicturess collection to an empty array (like clearcollPicturess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPicturess()
	{
		$this->collPicturess = new PropelObjectCollection();
		$this->collPicturess->setModel('Pictures');
	}

	/**
	 * Gets an array of Pictures objects which contain a foreign key that references this object.
	 *
	 * If the $criteria is not null, it is used to always fetch the results from the database.
	 * Otherwise the results are fetched from the database the first time, then cached.
	 * Next time the same method is called without $criteria, the cached collection is returned.
	 * If this Destination is new, it will return
	 * an empty collection or the current collection; the criteria is ignored on a new object.
	 *
	 * @param      Criteria $criteria optional Criteria object to narrow the query
	 * @param      PropelPDO $con optional connection object
	 * @return     PropelCollection|array Pictures[] List of Pictures objects
	 * @throws     PropelException
	 */
	public function getPicturess($criteria = null, PropelPDO $con = null)
	{
		if(null === $this->collPicturess || null !== $criteria) {
			if ($this->isNew() && null === $this->collPicturess) {
				// return empty collection
				$this->initPicturess();
			} else {
				$collPicturess = PicturesQuery::create(null, $criteria)
					->filterByDestination($this)
					->find($con);
				if (null !== $criteria) {
					return $collPicturess;
				}
				$this->collPicturess = $collPicturess;
			}
		}
		return $this->collPicturess;
	}

	/**
	 * Returns the number of related Pictures objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Pictures objects.
	 * @throws     PropelException
	 */
	public function countPicturess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if(null === $this->collPicturess || null !== $criteria) {
			if ($this->isNew() && null === $this->collPicturess) {
				return 0;
			} else {
				$query = PicturesQuery::create(null, $criteria);
				if($distinct) {
					$query->distinct();
				}
				return $query
					->filterByDestination($this)
					->count($con);
			}
		} else {
			return count($this->collPicturess);
		}
	}

	/**
	 * Method called to associate a Pictures object to this object
	 * through the Pictures foreign key attribute.
	 *
	 * @param      Pictures $l Pictures
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPictures(Pictures $l)
	{
		if ($this->collPicturess === null) {
			$this->initPicturess();
		}
		if (!$this->collPicturess->contains($l)) { // only add it if the **same** object is not already associated
			$this->collPicturess[]= $l;
			$l->setDestination($this);
		}
	}

	/**
	 * Clears the current object and sets all attributes to their default values
	 */
	public function clear()
	{
		$this->id = null;
		$this->location_id = null;
		$this->location_name = null;
		$this->region = null;
		$this->geolocation = null;
		$this->area = null;
		$this->elevation = null;
		$this->population = null;
		$this->infotext = null;
		$this->population_density = null;
		$this->airport_name = null;
		$this->airport_abbr = null;
		$this->airport_type = null;
		$this->timezone = null;
		$this->alreadyInSave = false;
		$this->alreadyInValidation = false;
		$this->clearAllReferences();
		$this->resetModified();
		$this->setNew(true);
		$this->setDeleted(false);
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPicturess) {
				foreach ((array) $this->collPicturess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPicturess = null;
	}

	/**
	 * Catches calls to virtual methods
	 */
	public function __call($name, $params)
	{
		// symfony_behaviors behavior
		if ($callable = sfMixer::getCallable('BaseDestination:' . $name))
		{
		  array_unshift($params, $this);
		  return call_user_func_array($callable, $params);
		}
		
		if (preg_match('/get(\w+)/', $name, $matches)) {
			$virtualColumn = $matches[1];
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
			// no lcfirst in php<5.3...
			$virtualColumn[0] = strtolower($virtualColumn[0]);
			if ($this->hasVirtualColumn($virtualColumn)) {
				return $this->getVirtualColumn($virtualColumn);
			}
		}
		return parent::__call($name, $params);
	}

} // BaseDestination
