<?php


/**
 * Base static class for performing query and update operations on the 'Playerstatus' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:30 2011
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BasePlayerstatusPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'Playerstatus';

	/** the related Propel class for this table */
	const OM_CLASS = 'Playerstatus';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Playerstatus';

	/** the related TableMap class for this table */
	const TM_CLASS = 'PlayerstatusTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 19;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the USER_ID field */
	const USER_ID = 'Playerstatus.USER_ID';

	/** the column name for the ON_FLIGHT field */
	const ON_FLIGHT = 'Playerstatus.ON_FLIGHT';

	/** the column name for the POINTS field */
	const POINTS = 'Playerstatus.POINTS';

	/** the column name for the BONUS field */
	const BONUS = 'Playerstatus.BONUS';

	/** the column name for the FLIGHT_POINTS field */
	const FLIGHT_POINTS = 'Playerstatus.FLIGHT_POINTS';

	/** the column name for the AVAILABLE_MILES field */
	const AVAILABLE_MILES = 'Playerstatus.AVAILABLE_MILES';

	/** the column name for the FLIGHTMILES_TOTAL field */
	const FLIGHTMILES_TOTAL = 'Playerstatus.FLIGHTMILES_TOTAL';

	/** the column name for the FLIGHTMILES_WEEK field */
	const FLIGHTMILES_WEEK = 'Playerstatus.FLIGHTMILES_WEEK';

	/** the column name for the FLIGHT_COUNT field */
	const FLIGHT_COUNT = 'Playerstatus.FLIGHT_COUNT';

	/** the column name for the HOMEBASE_FLIGHT field */
	const HOMEBASE_FLIGHT = 'Playerstatus.HOMEBASE_FLIGHT';

	/** the column name for the PLAYER_RANK field */
	const PLAYER_RANK = 'Playerstatus.PLAYER_RANK';

	/** the column name for the WEEK1 field */
	const WEEK1 = 'Playerstatus.WEEK1';

	/** the column name for the WEEK2 field */
	const WEEK2 = 'Playerstatus.WEEK2';

	/** the column name for the WEEK3 field */
	const WEEK3 = 'Playerstatus.WEEK3';

	/** the column name for the WEEK4 field */
	const WEEK4 = 'Playerstatus.WEEK4';

	/** the column name for the WEEK5 field */
	const WEEK5 = 'Playerstatus.WEEK5';

	/** the column name for the WEEK6 field */
	const WEEK6 = 'Playerstatus.WEEK6';

	/** the column name for the WEEK7 field */
	const WEEK7 = 'Playerstatus.WEEK7';

	/** the column name for the WEEK8 field */
	const WEEK8 = 'Playerstatus.WEEK8';

	/**
	 * An identiy map to hold any loaded instances of Playerstatus objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Playerstatus[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;
	
	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('UserId', 'OnFlight', 'Points', 'Bonus', 'FlightPoints', 'AvailableMiles', 'FlightmilesTotal', 'FlightmilesWeek', 'FlightCount', 'HomebaseFlight', 'PlayerRank', 'Week1', 'Week2', 'Week3', 'Week4', 'Week5', 'Week6', 'Week7', 'Week8', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('userId', 'onFlight', 'points', 'bonus', 'flightPoints', 'availableMiles', 'flightmilesTotal', 'flightmilesWeek', 'flightCount', 'homebaseFlight', 'playerRank', 'week1', 'week2', 'week3', 'week4', 'week5', 'week6', 'week7', 'week8', ),
		BasePeer::TYPE_COLNAME => array (self::USER_ID, self::ON_FLIGHT, self::POINTS, self::BONUS, self::FLIGHT_POINTS, self::AVAILABLE_MILES, self::FLIGHTMILES_TOTAL, self::FLIGHTMILES_WEEK, self::FLIGHT_COUNT, self::HOMEBASE_FLIGHT, self::PLAYER_RANK, self::WEEK1, self::WEEK2, self::WEEK3, self::WEEK4, self::WEEK5, self::WEEK6, self::WEEK7, self::WEEK8, ),
		BasePeer::TYPE_RAW_COLNAME => array ('USER_ID', 'ON_FLIGHT', 'POINTS', 'BONUS', 'FLIGHT_POINTS', 'AVAILABLE_MILES', 'FLIGHTMILES_TOTAL', 'FLIGHTMILES_WEEK', 'FLIGHT_COUNT', 'HOMEBASE_FLIGHT', 'PLAYER_RANK', 'WEEK1', 'WEEK2', 'WEEK3', 'WEEK4', 'WEEK5', 'WEEK6', 'WEEK7', 'WEEK8', ),
		BasePeer::TYPE_FIELDNAME => array ('User_id', 'on_flight', 'points', 'bonus', 'flight_points', 'available_miles', 'flightmiles_total', 'flightmiles_week', 'flight_count', 'homebase_flight', 'player_rank', 'week1', 'week2', 'week3', 'week4', 'week5', 'week6', 'week7', 'week8', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('UserId' => 0, 'OnFlight' => 1, 'Points' => 2, 'Bonus' => 3, 'FlightPoints' => 4, 'AvailableMiles' => 5, 'FlightmilesTotal' => 6, 'FlightmilesWeek' => 7, 'FlightCount' => 8, 'HomebaseFlight' => 9, 'PlayerRank' => 10, 'Week1' => 11, 'Week2' => 12, 'Week3' => 13, 'Week4' => 14, 'Week5' => 15, 'Week6' => 16, 'Week7' => 17, 'Week8' => 18, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('userId' => 0, 'onFlight' => 1, 'points' => 2, 'bonus' => 3, 'flightPoints' => 4, 'availableMiles' => 5, 'flightmilesTotal' => 6, 'flightmilesWeek' => 7, 'flightCount' => 8, 'homebaseFlight' => 9, 'playerRank' => 10, 'week1' => 11, 'week2' => 12, 'week3' => 13, 'week4' => 14, 'week5' => 15, 'week6' => 16, 'week7' => 17, 'week8' => 18, ),
		BasePeer::TYPE_COLNAME => array (self::USER_ID => 0, self::ON_FLIGHT => 1, self::POINTS => 2, self::BONUS => 3, self::FLIGHT_POINTS => 4, self::AVAILABLE_MILES => 5, self::FLIGHTMILES_TOTAL => 6, self::FLIGHTMILES_WEEK => 7, self::FLIGHT_COUNT => 8, self::HOMEBASE_FLIGHT => 9, self::PLAYER_RANK => 10, self::WEEK1 => 11, self::WEEK2 => 12, self::WEEK3 => 13, self::WEEK4 => 14, self::WEEK5 => 15, self::WEEK6 => 16, self::WEEK7 => 17, self::WEEK8 => 18, ),
		BasePeer::TYPE_RAW_COLNAME => array ('USER_ID' => 0, 'ON_FLIGHT' => 1, 'POINTS' => 2, 'BONUS' => 3, 'FLIGHT_POINTS' => 4, 'AVAILABLE_MILES' => 5, 'FLIGHTMILES_TOTAL' => 6, 'FLIGHTMILES_WEEK' => 7, 'FLIGHT_COUNT' => 8, 'HOMEBASE_FLIGHT' => 9, 'PLAYER_RANK' => 10, 'WEEK1' => 11, 'WEEK2' => 12, 'WEEK3' => 13, 'WEEK4' => 14, 'WEEK5' => 15, 'WEEK6' => 16, 'WEEK7' => 17, 'WEEK8' => 18, ),
		BasePeer::TYPE_FIELDNAME => array ('User_id' => 0, 'on_flight' => 1, 'points' => 2, 'bonus' => 3, 'flight_points' => 4, 'available_miles' => 5, 'flightmiles_total' => 6, 'flightmiles_week' => 7, 'flight_count' => 8, 'homebase_flight' => 9, 'player_rank' => 10, 'week1' => 11, 'week2' => 12, 'week3' => 13, 'week4' => 14, 'week5' => 15, 'week6' => 16, 'week7' => 17, 'week8' => 18, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. PlayerstatusPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(PlayerstatusPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      Criteria $criteria object containing the columns to add.
	 * @param      string   $alias    optional table alias
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria, $alias = null)
	{
		if (null === $alias) {
			$criteria->addSelectColumn(PlayerstatusPeer::USER_ID);
			$criteria->addSelectColumn(PlayerstatusPeer::ON_FLIGHT);
			$criteria->addSelectColumn(PlayerstatusPeer::POINTS);
			$criteria->addSelectColumn(PlayerstatusPeer::BONUS);
			$criteria->addSelectColumn(PlayerstatusPeer::FLIGHT_POINTS);
			$criteria->addSelectColumn(PlayerstatusPeer::AVAILABLE_MILES);
			$criteria->addSelectColumn(PlayerstatusPeer::FLIGHTMILES_TOTAL);
			$criteria->addSelectColumn(PlayerstatusPeer::FLIGHTMILES_WEEK);
			$criteria->addSelectColumn(PlayerstatusPeer::FLIGHT_COUNT);
			$criteria->addSelectColumn(PlayerstatusPeer::HOMEBASE_FLIGHT);
			$criteria->addSelectColumn(PlayerstatusPeer::PLAYER_RANK);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK1);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK2);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK3);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK4);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK5);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK6);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK7);
			$criteria->addSelectColumn(PlayerstatusPeer::WEEK8);
		} else {
			$criteria->addSelectColumn($alias . '.USER_ID');
			$criteria->addSelectColumn($alias . '.ON_FLIGHT');
			$criteria->addSelectColumn($alias . '.POINTS');
			$criteria->addSelectColumn($alias . '.BONUS');
			$criteria->addSelectColumn($alias . '.FLIGHT_POINTS');
			$criteria->addSelectColumn($alias . '.AVAILABLE_MILES');
			$criteria->addSelectColumn($alias . '.FLIGHTMILES_TOTAL');
			$criteria->addSelectColumn($alias . '.FLIGHTMILES_WEEK');
			$criteria->addSelectColumn($alias . '.FLIGHT_COUNT');
			$criteria->addSelectColumn($alias . '.HOMEBASE_FLIGHT');
			$criteria->addSelectColumn($alias . '.PLAYER_RANK');
			$criteria->addSelectColumn($alias . '.WEEK1');
			$criteria->addSelectColumn($alias . '.WEEK2');
			$criteria->addSelectColumn($alias . '.WEEK3');
			$criteria->addSelectColumn($alias . '.WEEK4');
			$criteria->addSelectColumn($alias . '.WEEK5');
			$criteria->addSelectColumn($alias . '.WEEK6');
			$criteria->addSelectColumn($alias . '.WEEK7');
			$criteria->addSelectColumn($alias . '.WEEK8');
		}
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PlayerstatusPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PlayerstatusPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		
		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Playerstatus
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = PlayerstatusPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return PlayerstatusPeer::populateObjects(PlayerstatusPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			PlayerstatusPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Playerstatus $value A Playerstatus object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Playerstatus $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getUserId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Playerstatus object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Playerstatus) {
				$key = (string) $value->getUserId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Playerstatus object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Playerstatus Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to Playerstatus
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * Retrieves the primary key from the DB resultset row 
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, an array of the primary key columns will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     mixed The primary key of the row
	 */
	public static function getPrimaryKeyFromRow($row, $startcol = 0)
	{
		return (int) $row[$startcol];
	}
	
	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = PlayerstatusPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = PlayerstatusPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = PlayerstatusPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				PlayerstatusPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Populates an object of the default type or an object that inherit from the default.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     array (Playerstatus object, last column rank)
	 */
	public static function populateObject($row, $startcol = 0)
	{
		$key = PlayerstatusPeer::getPrimaryKeyHashFromRow($row, $startcol);
		if (null !== ($obj = PlayerstatusPeer::getInstanceFromPool($key))) {
			// We no longer rehydrate the object, since this can cause data loss.
			// See http://www.propelorm.org/ticket/509
			// $obj->hydrate($row, $startcol, true); // rehydrate
			$col = $startcol + PlayerstatusPeer::NUM_COLUMNS;
		} else {
			$cls = PlayerstatusPeer::OM_CLASS;
			$obj = new $cls();
			$col = $obj->hydrate($row, $startcol);
			PlayerstatusPeer::addInstanceToPool($obj, $key);
		}
		return array($obj, $col);
	}

	/**
	 * Returns the number of rows matching criteria, joining the related User table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinUser(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PlayerstatusPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PlayerstatusPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PlayerstatusPeer::USER_ID, UserPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Playerstatus objects pre-filled with their User objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Playerstatus objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinUser(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PlayerstatusPeer::addSelectColumns($criteria);
		$startcol = (PlayerstatusPeer::NUM_COLUMNS - PlayerstatusPeer::NUM_LAZY_LOAD_COLUMNS);
		UserPeer::addSelectColumns($criteria);

		$criteria->addJoin(PlayerstatusPeer::USER_ID, UserPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		
		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PlayerstatusPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PlayerstatusPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = PlayerstatusPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PlayerstatusPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = UserPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = UserPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = UserPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					UserPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Playerstatus) to $obj2 (User)
				// one to one relationship
				$obj1->setUser($obj2);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(PlayerstatusPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			PlayerstatusPeer::addSelectColumns($criteria);
		}
		
		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		
		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(PlayerstatusPeer::USER_ID, UserPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Playerstatus objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Playerstatus objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		PlayerstatusPeer::addSelectColumns($criteria);
		$startcol2 = (PlayerstatusPeer::NUM_COLUMNS - PlayerstatusPeer::NUM_LAZY_LOAD_COLUMNS);

		UserPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (UserPeer::NUM_COLUMNS - UserPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(PlayerstatusPeer::USER_ID, UserPeer::ID, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasePlayerstatusPeer', $criteria, $con);
		}
		
		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = PlayerstatusPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = PlayerstatusPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://www.propelorm.org/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = PlayerstatusPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				PlayerstatusPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined User rows

			$key2 = UserPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = UserPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = UserPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					UserPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Playerstatus) to the collection in $obj2 (User)
				$obj1->setUser($obj2);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasePlayerstatusPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasePlayerstatusPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new PlayerstatusTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean $withPrefix Whether or not to return the path with the class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? PlayerstatusPeer::CLASS_DEFAULT : PlayerstatusPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a Playerstatus or Criteria object.
	 *
	 * @param      mixed $values Criteria or Playerstatus object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Playerstatus object
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Playerstatus or Criteria object.
	 *
	 * @param      mixed $values Criteria or Playerstatus object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(PlayerstatusPeer::USER_ID);
			$value = $criteria->remove(PlayerstatusPeer::USER_ID);
			if ($value) {
				$selectCriteria->add(PlayerstatusPeer::USER_ID, $value, $comparison);
			} else {
				$selectCriteria->setPrimaryTableName(PlayerstatusPeer::TABLE_NAME);
			}

		} else { // $values is Playerstatus object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		return BasePeer::doUpdate($selectCriteria, $criteria, $con);
	}

	/**
	 * Method to DELETE all rows from the Playerstatus table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(PlayerstatusPeer::TABLE_NAME, $con, PlayerstatusPeer::DATABASE_NAME);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			PlayerstatusPeer::clearInstancePool();
			PlayerstatusPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Playerstatus or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Playerstatus object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			PlayerstatusPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Playerstatus) { // it's a model object
			// invalidate the cache for this single object
			PlayerstatusPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(PlayerstatusPeer::USER_ID, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				PlayerstatusPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			PlayerstatusPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Playerstatus object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Playerstatus $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Playerstatus $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(PlayerstatusPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(PlayerstatusPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(PlayerstatusPeer::DATABASE_NAME, PlayerstatusPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Playerstatus
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = PlayerstatusPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(PlayerstatusPeer::DATABASE_NAME);
		$criteria->add(PlayerstatusPeer::USER_ID, $pk);

		$v = PlayerstatusPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(PlayerstatusPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(PlayerstatusPeer::DATABASE_NAME);
			$criteria->add(PlayerstatusPeer::USER_ID, $pks, Criteria::IN);
			$objs = PlayerstatusPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array();
	}
	
	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasePlayerstatusPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}
	
} // BasePlayerstatusPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasePlayerstatusPeer::buildTableMap();

