<?php



/**
 * Skeleton subclass for representing a row from the 'Flight' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Thu Mar  3 14:54:04 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Flight extends BaseFlight {

} // Flight
