<?php



/**
 * Skeleton subclass for representing a row from the 'Pictures' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Mon May 16 08:55:17 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Pictures extends BasePictures {
	public function __toString() {
		return $this->getId();
	}
} // Pictures
