<?php



/**
 * Skeleton subclass for performing query and update operations on the 'Pictures' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Mon May 16 08:55:17 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PicturesPeer extends BasePicturesPeer {

} // PicturesPeer
