generator:
  class: sfPropelGenerator
  param:
    model_class:           Destination
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Destination
    plural:                Destinations
    route_prefix:          destination
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
      filter:  
        class: false
      form:    ~
      edit:    ~
      new:     ~
