<?php



/**
 * This class defines the structure of the 'Friend' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:29 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class FriendTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FriendTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('Friend');
		$this->setPhpName('Friend');
		$this->setClassname('Friend');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('FB_ID', 'FbId', 'VARCHAR', false, 64, null);
		$this->addColumn('NAME', 'Name', 'VARCHAR', false, 64, null);
		$this->addColumn('IS_INVITED', 'IsInvited', 'BOOLEAN', false, null, null);
		$this->addForeignKey('LOCATION_ID', 'LocationId', 'INTEGER', 'Location', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Location', 'Location', RelationMap::MANY_TO_ONE, array('Location_id' => 'id', ), null, null);
    $this->addRelation('Flight', 'Flight', RelationMap::ONE_TO_MANY, array('id' => 'Friend_id', ), null, null);
    $this->addRelation('Friendrelation', 'Friendrelation', RelationMap::ONE_TO_MANY, array('id' => 'Friend_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // FriendTableMap
