<?php



/**
 * This class defines the structure of the 'Location' table.
 *
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue May 24 10:36:30 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class LocationTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.LocationTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('Location');
		$this->setPhpName('Location');
		$this->setClassname('Location');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('LOCATION_NAME', 'LocationName', 'VARCHAR', false, 256, null);
		$this->addColumn('LAT', 'Lat', 'FLOAT', false, null, null);
		$this->addColumn('LNG', 'Lng', 'FLOAT', false, null, null);
		$this->addColumn('COUNTRY', 'Country', 'VARCHAR', false, 128, null);
		$this->addColumn('TIMEZONE', 'Timezone', 'VARCHAR', false, 128, null);
		$this->addColumn('SWISS_DESTINATION', 'SwissDestination', 'BOOLEAN', false, null, null);
		$this->addColumn('FOREIGN_DESTINATION', 'ForeignDestination', 'BOOLEAN', false, null, null);
		$this->addColumn('NEAREST_DESTINATION', 'NearestDestination', 'VARCHAR', false, 128, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('FlightRelatedByStartLocationId', 'Flight', RelationMap::ONE_TO_MANY, array('id' => 'start_location_id', ), null, null);
    $this->addRelation('FlightRelatedByTargetLocationId', 'Flight', RelationMap::ONE_TO_MANY, array('id' => 'target_location_id', ), null, null);
    $this->addRelation('Friend', 'Friend', RelationMap::ONE_TO_MANY, array('id' => 'Location_id', ), null, null);
    $this->addRelation('User', 'User', RelationMap::ONE_TO_MANY, array('id' => 'Location_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // LocationTableMap
